// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP1cqnVQ4AsH5nuDpMfmZ05bi1L8U6NHo',
    appId: '1:699533188582:web:638968b0a963bd54154a27',
    messagingSenderId: '699533188582',
    projectId: 'project-req-app',
    authDomain: 'project-req-app.firebaseapp.com',
    storageBucket: 'project-req-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_yTMP53X0Y5VkLQvXkTX6o6-04dME8Q8',
    appId: '1:699533188582:android:f35a8f9ec78ac7d5154a27',
    messagingSenderId: '699533188582',
    projectId: 'project-req-app',
    storageBucket: 'project-req-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpTFWjSqCciGm-8eG8UHqFSEsxOQgdHjg',
    appId: '1:699533188582:ios:6aee294dcea83cc7154a27',
    messagingSenderId: '699533188582',
    projectId: 'project-req-app',
    storageBucket: 'project-req-app.appspot.com',
    iosClientId: '699533188582-8am24lese1dgj1dkdf35lir99m4aq0rm.apps.googleusercontent.com',
    iosBundleId: 'com.example.reqAppSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpTFWjSqCciGm-8eG8UHqFSEsxOQgdHjg',
    appId: '1:699533188582:ios:6aee294dcea83cc7154a27',
    messagingSenderId: '699533188582',
    projectId: 'project-req-app',
    storageBucket: 'project-req-app.appspot.com',
    iosClientId: '699533188582-8am24lese1dgj1dkdf35lir99m4aq0rm.apps.googleusercontent.com',
    iosBundleId: 'com.example.reqAppSystem',
  );
}
